import { Api } from './generated'
import type { ModelsAuthResponse } from './generated'

const API_BASE_URL = 'http://localhost:8080/api'
const AUTH_PATHS_TO_SKIP_REFRESH = ['/auth/login', '/auth/register', '/auth/refresh', '/auth/logout']

type RetryableRequestInit = RequestInit & { _isRetry?: boolean }

const isAuthPath = (url: string) => {
    return AUTH_PATHS_TO_SKIP_REFRESH.some((path) => url.includes(path))
}

const isAuthResponse = (value: unknown): value is ModelsAuthResponse => {
    return typeof value === 'object' && value !== null && 'accessToken' in value && 'user' in value
}

let refreshInFlight: Promise<boolean> | null = null

const refreshAccessToken = async (): Promise<boolean> => {
    if (!refreshInFlight) {
        refreshInFlight = (async () => {
            try {
                const refreshResponse = await fetch(`${API_BASE_URL}/auth/refresh`, {
                    method: 'POST',
                    credentials: 'include',
                })
                if (!refreshResponse.ok) {
                    return false
                }

                const payload: unknown = await refreshResponse.json()
                if (!isAuthResponse(payload) || typeof payload.accessToken !== 'string') {
                    return false
                }

                setApiAuthToken(payload.accessToken)
                return true
            } catch (error) {
                console.error('Failed to refresh access token', error)
                return false
            } finally {
                refreshInFlight = null
            }
        })()
    }

    return refreshInFlight
}

const customFetch: typeof fetch = async (input, init = {}) => {
    const requestUrl = typeof input === 'string' ? input : input.toString()
    const requestInit = init as RetryableRequestInit

    const response = await fetch(input, {
        ...requestInit,
        credentials: 'include',
    })

    if (
        response.status !== 401 ||
        requestInit._isRetry ||
        isAuthPath(requestUrl)
    ) {
        return response
    }

    const refreshed = await refreshAccessToken()
    if (!refreshed) {
        return response
    }

    return fetch(input, {
        ...requestInit,
        _isRetry: true,
        credentials: 'include',
    } as RetryableRequestInit)
}

/**
 * Autogenerated API client (swagger-typescript-api).
 *
 * Note: codegen runs via `npm run gen` (and automatically via predev/prebuild).
 */
export const api = new Api({
    baseUrl: API_BASE_URL,
    customFetch,
    baseApiParams: {
        secure: true,
        credentials: 'include',
    },
    securityWorker: (token: string | null) => {
        if (!token) {
            return {}
        }

        return {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        }
    },
})

export const setApiAuthToken = (token: string | null) => {
    api.setSecurityData(token)
}


