import { Api } from './generated'

const API_BASE_URL = 'http://localhost:8080/api'

/**
 * Autogenerated API client (swagger-typescript-api).
 *
 * Note: codegen runs via `npm run gen` (and automatically via predev/prebuild).
 */
export const api = new Api({
    baseUrl: API_BASE_URL,
    baseApiParams: {
        secure: true,
    },
    securityWorker: (token: string | null) => {
        if (!token) {
            return {}
        }

        return {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        }
    },
})

export const setApiAuthToken = (token: string | null) => {
    api.setSecurityData(token)
}


